version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: belgrade-mama-db-prod
    environment:
      POSTGRES_USER: ${DB_USER:-marketplace}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-marketplace}
      POSTGRES_DB: ${DB_NAME:-marketplace}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: belgrade-mama-api-prod
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://${DB_USER:-marketplace}:${DB_PASSWORD:-marketplace}@postgres:5432/${DB_NAME:-marketplace}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - api_uploads:/app/uploads

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:4000}
    container_name: belgrade-mama-web-prod
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  api_uploads:
