services:
  # Backend API
  - type: web
    name: belgrade-mama-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd apps/api && npm install && npx prisma generate
    startCommand: cd apps/api && npx prisma migrate deploy && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://belgrade-mama-api.onrender.com
      - key: FRONTEND_URL
        value: https://belgrade-mama-web.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: belgrade-mama-web
    env: static
    region: frankfurt
    plan: free
    buildCommand: cd apps/web && npm install && npm run build
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://belgrade-mama-api.onrender.com
