services:
  # Backend API
  - type: web
    name: belgrade-mama-api
    env: node
    buildCommand: cd apps/api && pnpm install && pnpm prisma generate
    startCommand: cd apps/api && pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://belgrade-mama.vercel.app
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false

  # PostgreSQL Database
  - type: pserv
    name: belgrade-mama-db
    env: docker
    plan: starter
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
