services:
  # Backend API
  - type: web
    name: belgrade-mama-api
    env: node
    region: frankfurt
    plan: free
    rootDir: apps/api
    buildCommand: pnpm install && pnpm prisma generate
    startCommand: pnpm prisma migrate deploy && pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://belgrade-mama-api.onrender.com
      - key: FRONTEND_URL
        value: https://belgrade-mama-web.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: belgrade-mama-web
    env: static
    region: frankfurt
    plan: free
    rootDir: apps/web
    buildCommand: pnpm install && pnpm build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://belgrade-mama-api.onrender.com
